version: '3'

services: 
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    platform: linux/amd64
    container_name: nginx
    volumes:
      - .:/hannuri     
      - ./nginx:/etc/nginx/
      - ${host_path_to_ssl}:/etc/letsencrypt
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - 80:80
      - 443:443
    links:
      - backend:backend
  
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    platform: linux/amd64
    container_name: backend
    volumes:
      - ./backend:/backend
    command : bash -c "cd /backend && gunicorn -w 3 --bind 0:2102 backend.wsgi"
    ports:
      - 2102:2102
