version: 0.0
os: linux
files:
  - source: /backend
    destination: /home/hannuri/backend

file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"

hooks:
  ApplicationStart:
    - location: script.sh
