version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    platform: linux/amd64
    container_name: hannuri-nginx
    volumes:
      - ${STATIC_FILE_ROOT}:/static
      - ${HOST_PATH_TO_SSL}:/etc/letsencrypt
      - ./nginx:/etc/nginx/
    environment:
      - FRONT_DOMAIN=${FRONT_DOMAIN}
      - API_DOMAIN=${API_DOMAIN}
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - 80:80
      - 443:443
    links:
      - backend:backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    platform: linux/amd64
    container_name: hannuri-backend
    volumes:
      - ${DB_ROOT}/db.sqlite3:/backend/db.sqlite3
      - ${STATIC_FILE_ROOT}/uploads:/backend/uploads
      - ${SECRET_FILE_ROOT}:/backend/secret
      - ./backend:/backend
    command: bash -c "cd /backend && python3 manage.py migrate && gunicorn -w 3 --bind 0:2102 backend.wsgi"
    ports:
      - 2102:2102
