name: CI-CD-Frontend

on:
  workflow_dispatch:
    branches:
      - master
  push:
    paths:
      - "frontend/**"
    branches:
      - master

env:
  S3_BUCKET_NAME: hannuri
  CODE_DEPLOY_APPLICATION_NAME: deploy-hannuri-front
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: hannuri-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_API_DOMAIN: ${{ secrets.API_DOMAIN }}/
          envkey_REACT_APP_GOOGLE_OAUTH_LOGIN_URL: ${{ secrets.GOOGLE_OAUTH_LOGIN_URL }}
          envkey_REACT_APP_GOOGLE_OAUTH_SIGNIN_URL: ${{ secrets.GOOGLE_OAUTH_SIGNIN_URL }}
          directory: ./frontend
          file_name: .env
          fail_on_empty: true

      - name: Build
        working-directory: ./frontend
        run: |
          yarn
          yarn build
        shell: bash

      - name: Make zip file
        working-directory: ./frontend
        run: |
          cp ../.deploy/appspec/front.yml ./appspec.yml
          zip -r ./deploy-frontend.zip ./build appspec.yml
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        working-directory: ./frontend
        run: |
          aws s3 cp --region ${{ secrets.AWS_REGION }} ./deploy-frontend.zip s3://$S3_BUCKET_NAME/deploy-frontend.zip

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=deploy-frontend.zip
