name: CI-CD-Server

on:
  workflow_dispatch:
    branches:
      - master
  push:
    paths:
      - "nginx/**"
      - "docker-compose.yml"
    branches:
      - master

env:
  S3_BUCKET_NAME: hannuri
  CODE_DEPLOY_APPLICATION_NAME: deploy-hannuri-server
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: hannuri-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_HOST_PATH_TO_SSL: ${{ secrets.HOST_PATH_TO_SSL }}
          envkey_STATIC_FILE_ROOT: ${{ secrets.STATIC_FILE_ROOT }}
          envkey_SECRET_FILE_ROOT: ${{ secrets.SECRET_FILE_ROOT }}
          envkey_FRONT_DOMAIN: ${{ secrets.FRONT_DOMAIN }}
          envkey_API_DOMAIN: ${{ secrets.API_DOMAIN }}
          directory: ./
          file_name: .env
          fail_on_empty: true

      - name: Make zip soure code
        run: |
          cp ./.deploy/appspec/server.yml ./appspec.yml
          cp ./.deploy/docker-compose.yml ./docker-compose.yml
          cp ./.deploy/script/application-restart.sh ./script.sh
          zip -r ./deploy-server.zip ./nginx docker-compose.yml appspec.yml .env script.sh
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp --region ${{ secrets.AWS_REGION }} ./deploy-server.zip s3://$S3_BUCKET_NAME/deploy-server.zip

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=deploy-server.zip
